services:
  - type: web
    name: pumpradar
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_EMAIL
        value: "mailto:admin@pumpradar.app"
